
import type { Product, Category, Order } from "./types";
import { PlaceHolderImages } from "./placeholder-images";

export const categories: Category[] = [
  { id: "womens-wear", name: "Women's Wear", imageUrl: "https://picsum.photos/seed/cat1/400/400", imageHint: "women clothing" },
  { id: "mens-wear", name: "Men's Wear", imageUrl: "https://picsum.photos/seed/cat2/400/400", imageHint: "men clothing" },
  { id: "unisex", name: "Unisex", imageUrl: "https://picsum.photos/seed/cat3/400/400", imageHint: "unisex fashion" },
  { id: "shoes", name: "Shoes", imageUrl: "https://picsum.photos/seed/cat4/400/400", imageHint: "fashion shoes" },
  { id: "bags", name: "Bags", imageUrl: "https://picsum.photos/seed/cat5/400/400", imageHint: "handbag" },
  { id: "jewelry", name: "Jewelry", imageUrl: "https://picsum.photos/seed/cat6/400/400", imageHint: "jewelry necklace" },
  { id: "accessories", name: "Accessories", imageUrl: "https://picsum.photos/seed/cat7/400/400", imageHint: "fashion accessories" },
  { id: "sewing-materials", name: "Sewing Materials", imageUrl: "https://picsum.photos/seed/cat8/400/400", imageHint: "fabric threads" },
];

export const products: Product[] = [
  {
    id: "1",
    name: "Elegant Ankara Dress",
    slug: "elegant-ankara-dress",
    description: PlaceHolderImages.find(p => p.id === "product-1")?.description || "",
    price: 120.0,
    category: "womens-wear",
    imageUrl: PlaceHolderImages.find(p => p.id === "product-1")?.imageUrl || "https://picsum.photos/seed/fashion1/600/800",
    imageHint: PlaceHolderImages.find(p => p.id === "product-1")?.imageHint || "woman fashion",
    stock: 15,
  },
  {
    id: "2",
    name: "Modern Agbada",
    slug: "modern-agbada",
    description: PlaceHolderImages.find(p => p.id === "product-2")?.description || "",
    price: 250.0,
    category: "mens-wear",
    imageUrl: PlaceHolderImages.find(p => p.id === "product-2")?.imageUrl || "https://picsum.photos/seed/fashion2/600/800",
    imageHint: PlaceHolderImages.find(p => p.id === "product-2")?.imageHint || "man fashion",
    stock: 10,
  },
  {
    id: "3",
    name: "Hand-beaded Aso-Oke",
    slug: "hand-beaded-aso-oke",
    description: PlaceHolderImages.find(p => p.id === "product-3")?.description || "",
    price: 300.0,
    category: "sewing-materials",
    imageUrl: PlaceHolderImages.find(p => p.id === "product-3")?.imageUrl || "https://picsum.photos/seed/fashion3/600/800",
    imageHint: PlaceHolderImages.find(p => p.id === "product-3")?.imageHint || "fabric pattern",
    stock: 5,
  },
  {
    id: "4",
    name: "Chic Dashiki Shirt",
    slug: "chic-dashiki-shirt",
    description: PlaceHolderImages.find(p => p.id === "product-4")?.description || "",
    price: 75.0,
    category: "unisex",
    imageUrl: PlaceHolderImages.find(p => p.id === "product-4")?.imageUrl || "https://picsum.photos/seed/fashion4/600/800",
    imageHint: PlaceHolderImages.find(p => p.id === "product-4")?.imageHint || "unisex shirt",
    stock: 20,
  },
  {
    id: "5",
    name: "Flowing Boubou Gown",
    slug: "flowing-boubou-gown",
    description: PlaceHolderImages.find(p => p.id === "product-5")?.description || "",
    price: 180.0,
    category: "womens-wear",
    imageUrl: PlaceHolderImages.find(p => p.id === "product-5")?.imageUrl || "https://picsum.photos/seed/fashion5/600/800",
    imageHint: PlaceHolderImages.find(p => p.id === "product-5")?.imageHint || "woman dress",
    stock: 12,
  },
  {
    id: "6",
    name: "Senator Style Suit",
    slug: "senator-style-suit",
    description: PlaceHolderImages.find(p => p.id === "product-6")?.description || "",
    price: 220.0,
    category: "mens-wear",
    imageUrl: PlaceHolderImages.find(p => p.id === "product-6")?.imageUrl || "https://picsum.photos/seed/fashion6/600/800",
    imageHint: PlaceHolderImages.find(p => p.id === "product-6")?.imageHint || "man suit",
    stock: 8,
  },
   {
    id: "7",
    name: "Iro and Buba Set",
    slug: "iro-and-buba-set",
    description: PlaceHolderImages.find(p => p.id === "product-7")?.description || "",
    price: 150.0,
    category: "womens-wear",
    imageUrl: PlaceHolderImages.find(p => p.id === "product-7")?.imageUrl || "https://picsum.photos/seed/fashion7/600/800",
    imageHint: PlaceHolderImages.find(p => p.id === "product-7")?.imageHint || "traditional outfit",
    stock: 14,
  },
   {
    id: "8",
    name: "Kente Patterned Skirt",
    slug: "kente-patterned-skirt",
    description: PlaceHolderImages.find(p => p.id === "product-8")?.description || "",
    price: 65.0,
    category: "womens-wear",
    imageUrl: PlaceHolderImages.find(p => p.id === "product-8")?.imageUrl || "https://picsum.photos/seed/fashion8/600/800",
    imageHint: PlaceHolderImages.find(p => p.id === "product-8")?.imageHint || "woman skirt",
    stock: 25,
  },
];

export const orders: Order[] = [
  {
    id: "ORD-001",
    customerName: "Adaeze Nwosu",
    customerEmail: "ada.nwosu@example.com",
    date: "2024-07-20",
    status: "Shipped",
    total: 120.0,
    items: [{ productId: "1", productName: "Elegant Ankara Dress", quantity: 1, price: 120.0 }],
  },
  {
    id: "ORD-002",
    customerName: "Bolanle Adeboye",
    customerEmail: "bola.ade@example.com",
    date: "2024-07-19",
    status: "Processing",
    total: 325.0,
    items: [
      { productId: "2", productName: "Modern Agbada", quantity: 1, price: 250.0 },
      { productId: "4", productName: "Chic Dashiki Shirt", quantity: 1, price: 75.0 },
    ],
  },
  {
    id: "ORD-003",
    customerName: "Chidi Okoro",
    customerEmail: "chidi.okoro@example.com",
    date: "2024-07-18",
    status: "Delivered",
    total: 220.0,
    items: [{ productId: "6", productName: "Senator Style Suit", quantity: 1, price: 220.0 }],
  },
];

    